// ignore_for_file: non_constant_identifier_names, file_names

/*
 للاسف تم استخدام هده الطريقه بسبب التحديث الجديد ل فلانر
 */

import '../main.dart';

Map ar = {
  "1": "تخطي",
  "2": "تسجيل دخول",
  "3": 'الايميل او رقم الهاتف',
  "4": 'الرمز السري',
  "5": 'نسيت كلمة السر؟',
  "6": "الغاء",
  "7": "يمكنك تسجيل الدخول من الحسابات التالية",
  "8": "فيسبوك",
  "9": "قوقل",
  "10": 'الاشتراك',
  "11": "اذا لم تمتلك حساب فقم بعملية",
  "12": 'الإسم الأول',
  "13": 'الإسم الثاني',
  "14": 'البريد الإلكتروني',
  "15": 'رقم الهاتف',
  "16": 'الرمز السري',
  "17": 'تأكيد الرمز السري',
  "18": "تسجيل اشتراك",
  "19": 'او',
  "20": 'العروض',
  "21": 'السيارات',
  "22": "قطع غيار",
  "23": "الإطارات",
  "24": "دراجات نارية",
  "25": "الشاحنات",
  "26": "القوارب",
  "27": "اليوم",
  "28": "الأمس",
  "29": "أقدم",
  "30": "البحث",
  "31": 'اكتب شي للبحث عنه',
  "32": "من النتائج",
  "33": "التصنيف",
  "34": "المفضله",
  "35": "الإعلانات",
  "36": 'الملف الشخصي',
  "37": "إنشاء اعلان",
  "38": "اختر نوع الإعلان الذي تريد نشره علي التطبيق",
  "39": "تعديل الملف الشخصي",
  "40": "تغيير كلمة السر",
  "41": 'الإسم الأول',
  "42": 'الإسم الثاني',
  "43": 'رقم الهاتف',
  "44": "إلغاء",
  "45": 'حفظ',
  "46": "يمكنك تغير كلمة السر و إعادة تعين كلمة سرج جديدة",
  "47": 'الرمز السري الحالي',
  "48": 'الرمز السري الجديد',
  "49": 'إعادة كتابه الرمز السري الجديد',
  "50": "الإعدادات",
  "51": "الوضع الليلي",
  "52":
      'برنامج auto car هو برنامج متخصص ببيع مختلف انواع المركبات وقطع الغيار في مكان واحد.',
  "53": "لغة التطبيق",
  "54": "تسجيل الخروج",
  "55": "إنشاء اعلان",
  "56": 'عنوان الإعلان',
  "57": "فئة السيارة",
  "58": "نوع السيارة",
  "59": "نوع الوقود",
  "60": "هجين",
  "61": "إلكتروني",
  "62": "بترول",
  "63": "ديزل",
  "64": "الناقل",
  "65": "لون السيارة",
  "66": "المدينة",
  "67": "سنة الصنع",
  "68": "حالة السيارة",
  "69": "السيارة جديدة",
  "70": "السيارة مستعملة",
  "71": "الصور",
  "72": 'تعدد المركبة',
  "73": 'الوصف',
  "74": "نوع الغيار",
  "75": "حالة الغيار",
  "76": "الغيار جديدة",
  "77": "الغيار مستعملة",
  "78": "السعر",
  "79": "اختار سعر قطع الغيار",
  "80": "نشر",
  "81": "العلامة التجارية",
  "82": "حالة الإطارات",
  "83": "جديدة",
  "84": "مستعملة",
  "85": 'الحجم',
  "86": "اختار سعر الإطار",
  "87": "فئة الدراجة",
  "88": "نوع الدراجة",
  "89": "حالة الدراجة",
  "90": "سنة الصنع",
  "91": "قدرة المحرك",
  "92": "نوع القارب",
  "93": "حالة القارب",
  "94": "القارب جديدة",
  "95": "اختار سعر القارب",
  "96": "نوع الشاحنة",
  "97": "حالة الشاحنة",
  "98": "التاريخ النشر : ",
  "99": "المعلومات",
  "100": "الحالة  ",
  "101": "اللون",
  "102": "الإضافات",
};
Map en = {
  "1": "Skip",
  "2": "Log in",
  "3": "Email or Phone Number",
  "4": "Password",
  "5": "Forgot Password?",
  "6": "Cancel",
  "7": "You can log in using the following accounts",
  "8": "Facebook",
  "9": "Google",
  "10": "Sign up",
  "11": "If you don't have an account,",
  "12": "First Name",
  "13": "Last Name",
  "14": "Email",
  "15": "Phone Number",
  "16": "Password",
  "17": "Confirm Password",
  "18": "Sign Up",
  "19": "or",
  "20": "Offers",
  "21": "Cars",
  "22": "Spare Parts",
  "23": "Tires",
  "24": "Motorcycles",
  "25": "Trucks",
  "26": "Boats",
  "27": "Today",
  "28": "Yesterday",
  "29": "Oldest",
  "30": "Search",
  "31": "Type something to search for",
  "32": "Results",
  "33": "Category",
  "34": "Favorites",
  "35": "Ads",
  "36": "Profile",
  "37": "Create Ad",
  "38": "Choose the type of ad you want to post on the app",
  "39": "Edit Profile",
  "40": "Change Password",
  "41": "First Name",
  "42": "Last Name",
  "43": "Phone Number",
  "44": "Cancel",
  "45": "Save",
  "46": "You can change your password and reset your password",
  "47": "Current Password",
  "48": "New Password",
  "49": "Re-enter New Password",
  "50": "Settings",
  "51": "Dark Mode",
  "52":
      "Auto Car is a specialized program for selling various types of vehicles and spare parts in one place.",
  "53": "App Language",
  "54": "Log Out",
  "55": "Create Ad",
  "56": "Ad Title",
  "57": "Car Category",
  "58": "Car Type",
  "59": "Fuel Type",
  "60": "Hybrid",
  "61": "Electric",
  "62": "Gasoline",
  "63": "Diesel",
  "64": "Transmission",
  "65": "Car Color",
  "66": "City",
  "67": "Year of Manufacture",
  "68": "Car Condition",
  "69": "New Car",
  "70": "Used Car",
  "71": "Photos",
  "72": "Vehicle Multiplicity",
  "73": "Description",
  "74": "Spare Part Type",
  "75": "Spare Part Condition",
  "76": "New Spare Part",
  "77": "Used Spare Part",
  "78": "Price",
  "79": "Choose the spare part price",
  "80": "Publish",
  "81": "Brand",
  "82": "Tire Condition",
  "83": "New",
  "84": "Used",
  "85": "Size",
  "86": "Choose the tire price",
  "87": "Bike Category",
  "88": "Bike Type",
  "89": "Bike Condition",
  "90": "Year of Manufacture",
  "91": "Engine Capacity",
  "92": "Boat Type",
  "93": "Boat Condition",
  "94": "New Boat",
  "95": "Choose the boat price",
  "96": "Truck Type",
  "97": "Truck Condition",
  "98": "Published Date: ",
  "99": "Information",
  "100": "Status  ",
  "101": "Color ",
  "102": "Additions ",
};
bool IsAR() {
  if (language == "AR") {
    return true;
  } else {
    return false;
  }
}
